[versions]
kotlin = "2.2.21"
vck = "5.9.0"
testballoon = "0.7.1-K2.2.21"
asp = "20251109"

[libraries]
vck = { module = "at.asitplus.wallet:vck", version.ref = "vck" }
[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }

