[versions]
kotlin = "2.3.0"
vck = "5.10.0"
testballoon = "0.7.1-K2.3.0"
asp = "20251217"

[libraries]
vck = { module = "at.asitplus.wallet:vck", version.ref = "vck" }
[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }

