[versions]
kotlin = "2.2.20"
vck = "5.9.0-SNAPSHOT"
testballoon = "0.6.3-K2.2.20-SNAPSHOT"
asp = "20251017"

[libraries]
vck = { module = "at.asitplus.wallet:vck", version.ref = "vck" }
[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }

